### ISSUE TITLE
80 character al say

### ISSUE THREAD

**Issue by amleaver** [McInkay/cowsay#2]
Are there any plans to add an 80 character al-say so I can use it in git commits?

**Comment by AlMcKinlay** [comment]
No, sorry.

**Comment by chooban** [comment]
I think you should reconsider this.

**Comment by amleaver** [comment]
@chooban I am considering forking this project to add 80 character al-say, I'll keep you updated.

**Comment by AlMcKinlay** [comment]
I am open to contributions that would include it, but I wouldn't be doing it myself.
